/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgOrgIdRouteImport } from './routes/org/$orgId'
import { Route as OrgOrgIdIndexRouteImport } from './routes/org/$orgId/index'
import { Route as OrgOrgIdProjectProjectIdRouteImport } from './routes/org/$orgId/project/$projectId'
import { Route as OrgOrgIdProjectProjectIdIndexRouteImport } from './routes/org/$orgId/project/$projectId/index'
import { Route as OrgOrgIdProjectProjectIdRuntimesRouteImport } from './routes/org/$orgId/project/$projectId/runtimes'
import { Route as OrgOrgIdProjectProjectIdEstimationRouteImport } from './routes/org/$orgId/project/$projectId/estimation'
import { Route as OrgOrgIdProjectProjectIdAddonsRouteImport } from './routes/org/$orgId/project/$projectId/addons'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdRoute = OrgOrgIdRouteImport.update({
  id: '/org/$orgId',
  path: '/org/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdIndexRoute = OrgOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdProjectProjectIdRoute =
  OrgOrgIdProjectProjectIdRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => OrgOrgIdRoute,
  } as any)
const OrgOrgIdProjectProjectIdIndexRoute =
  OrgOrgIdProjectProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgOrgIdProjectProjectIdRoute,
  } as any)
const OrgOrgIdProjectProjectIdRuntimesRoute =
  OrgOrgIdProjectProjectIdRuntimesRouteImport.update({
    id: '/runtimes',
    path: '/runtimes',
    getParentRoute: () => OrgOrgIdProjectProjectIdRoute,
  } as any)
const OrgOrgIdProjectProjectIdEstimationRoute =
  OrgOrgIdProjectProjectIdEstimationRouteImport.update({
    id: '/estimation',
    path: '/estimation',
    getParentRoute: () => OrgOrgIdProjectProjectIdRoute,
  } as any)
const OrgOrgIdProjectProjectIdAddonsRoute =
  OrgOrgIdProjectProjectIdAddonsRouteImport.update({
    id: '/addons',
    path: '/addons',
    getParentRoute: () => OrgOrgIdProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/org/$orgId': typeof OrgOrgIdRouteWithChildren
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/org/$orgId/project/$projectId': typeof OrgOrgIdProjectProjectIdRouteWithChildren
  '/org/$orgId/project/$projectId/addons': typeof OrgOrgIdProjectProjectIdAddonsRoute
  '/org/$orgId/project/$projectId/estimation': typeof OrgOrgIdProjectProjectIdEstimationRoute
  '/org/$orgId/project/$projectId/runtimes': typeof OrgOrgIdProjectProjectIdRuntimesRoute
  '/org/$orgId/project/$projectId/': typeof OrgOrgIdProjectProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/org/$orgId': typeof OrgOrgIdIndexRoute
  '/org/$orgId/project/$projectId/addons': typeof OrgOrgIdProjectProjectIdAddonsRoute
  '/org/$orgId/project/$projectId/estimation': typeof OrgOrgIdProjectProjectIdEstimationRoute
  '/org/$orgId/project/$projectId/runtimes': typeof OrgOrgIdProjectProjectIdRuntimesRoute
  '/org/$orgId/project/$projectId': typeof OrgOrgIdProjectProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/org/$orgId': typeof OrgOrgIdRouteWithChildren
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/org/$orgId/project/$projectId': typeof OrgOrgIdProjectProjectIdRouteWithChildren
  '/org/$orgId/project/$projectId/addons': typeof OrgOrgIdProjectProjectIdAddonsRoute
  '/org/$orgId/project/$projectId/estimation': typeof OrgOrgIdProjectProjectIdEstimationRoute
  '/org/$orgId/project/$projectId/runtimes': typeof OrgOrgIdProjectProjectIdRuntimesRoute
  '/org/$orgId/project/$projectId/': typeof OrgOrgIdProjectProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/org/$orgId'
    | '/org/$orgId/'
    | '/org/$orgId/project/$projectId'
    | '/org/$orgId/project/$projectId/addons'
    | '/org/$orgId/project/$projectId/estimation'
    | '/org/$orgId/project/$projectId/runtimes'
    | '/org/$orgId/project/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/org/$orgId'
    | '/org/$orgId/project/$projectId/addons'
    | '/org/$orgId/project/$projectId/estimation'
    | '/org/$orgId/project/$projectId/runtimes'
    | '/org/$orgId/project/$projectId'
  id:
    | '__root__'
    | '/'
    | '/org/$orgId'
    | '/org/$orgId/'
    | '/org/$orgId/project/$projectId'
    | '/org/$orgId/project/$projectId/addons'
    | '/org/$orgId/project/$projectId/estimation'
    | '/org/$orgId/project/$projectId/runtimes'
    | '/org/$orgId/project/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgOrgIdRoute: typeof OrgOrgIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId': {
      id: '/org/$orgId'
      path: '/org/$orgId'
      fullPath: '/org/$orgId'
      preLoaderRoute: typeof OrgOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/': {
      id: '/org/$orgId/'
      path: '/'
      fullPath: '/org/$orgId/'
      preLoaderRoute: typeof OrgOrgIdIndexRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/project/$projectId': {
      id: '/org/$orgId/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/org/$orgId/project/$projectId'
      preLoaderRoute: typeof OrgOrgIdProjectProjectIdRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/project/$projectId/': {
      id: '/org/$orgId/project/$projectId/'
      path: '/'
      fullPath: '/org/$orgId/project/$projectId/'
      preLoaderRoute: typeof OrgOrgIdProjectProjectIdIndexRouteImport
      parentRoute: typeof OrgOrgIdProjectProjectIdRoute
    }
    '/org/$orgId/project/$projectId/runtimes': {
      id: '/org/$orgId/project/$projectId/runtimes'
      path: '/runtimes'
      fullPath: '/org/$orgId/project/$projectId/runtimes'
      preLoaderRoute: typeof OrgOrgIdProjectProjectIdRuntimesRouteImport
      parentRoute: typeof OrgOrgIdProjectProjectIdRoute
    }
    '/org/$orgId/project/$projectId/estimation': {
      id: '/org/$orgId/project/$projectId/estimation'
      path: '/estimation'
      fullPath: '/org/$orgId/project/$projectId/estimation'
      preLoaderRoute: typeof OrgOrgIdProjectProjectIdEstimationRouteImport
      parentRoute: typeof OrgOrgIdProjectProjectIdRoute
    }
    '/org/$orgId/project/$projectId/addons': {
      id: '/org/$orgId/project/$projectId/addons'
      path: '/addons'
      fullPath: '/org/$orgId/project/$projectId/addons'
      preLoaderRoute: typeof OrgOrgIdProjectProjectIdAddonsRouteImport
      parentRoute: typeof OrgOrgIdProjectProjectIdRoute
    }
  }
}

interface OrgOrgIdProjectProjectIdRouteChildren {
  OrgOrgIdProjectProjectIdAddonsRoute: typeof OrgOrgIdProjectProjectIdAddonsRoute
  OrgOrgIdProjectProjectIdEstimationRoute: typeof OrgOrgIdProjectProjectIdEstimationRoute
  OrgOrgIdProjectProjectIdRuntimesRoute: typeof OrgOrgIdProjectProjectIdRuntimesRoute
  OrgOrgIdProjectProjectIdIndexRoute: typeof OrgOrgIdProjectProjectIdIndexRoute
}

const OrgOrgIdProjectProjectIdRouteChildren: OrgOrgIdProjectProjectIdRouteChildren =
  {
    OrgOrgIdProjectProjectIdAddonsRoute: OrgOrgIdProjectProjectIdAddonsRoute,
    OrgOrgIdProjectProjectIdEstimationRoute:
      OrgOrgIdProjectProjectIdEstimationRoute,
    OrgOrgIdProjectProjectIdRuntimesRoute:
      OrgOrgIdProjectProjectIdRuntimesRoute,
    OrgOrgIdProjectProjectIdIndexRoute: OrgOrgIdProjectProjectIdIndexRoute,
  }

const OrgOrgIdProjectProjectIdRouteWithChildren =
  OrgOrgIdProjectProjectIdRoute._addFileChildren(
    OrgOrgIdProjectProjectIdRouteChildren,
  )

interface OrgOrgIdRouteChildren {
  OrgOrgIdIndexRoute: typeof OrgOrgIdIndexRoute
  OrgOrgIdProjectProjectIdRoute: typeof OrgOrgIdProjectProjectIdRouteWithChildren
}

const OrgOrgIdRouteChildren: OrgOrgIdRouteChildren = {
  OrgOrgIdIndexRoute: OrgOrgIdIndexRoute,
  OrgOrgIdProjectProjectIdRoute: OrgOrgIdProjectProjectIdRouteWithChildren,
}

const OrgOrgIdRouteWithChildren = OrgOrgIdRoute._addFileChildren(
  OrgOrgIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgOrgIdRoute: OrgOrgIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
